### ISSUE TITLE
rust webpack not looking for the correct wasm filename and not webpack not exporting the cwrap function

### ISSUE THREAD

**Issue by benkonz** [bwasty/rust-wasm-webpack-template#2]
Hi, I just cloned the code for this project and I was having some trouble getting everything up and running.  I ran `npm install` and `npm build` on the code, but when I started up a local server and looked at my browser's error logs, I was getting a 404 error on the url `rust_wasm_webpack_template` while loading the wasm module. The correct name of the wasm file generated by npm run build is `rust-wasm-webpack-template`. After renaming the file to what the bundle.js was expecting, my browser ran the main function, but crashed when I tried to call the cwrap function, but during the emscripten/cargo compilation the cwrap function is never exported, so the module object cannot load it. I was able to fix this by adding a .cargo directory in the same directory as the Cargo.toml and adding a file named config with this text:
```
[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-args=-s EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap']" ,
]
```
I can put in a pull request for the config file, but I have no idea how to fix the filename issue. Any thoughts?

OS: Linux Mint
Rust Version: 1.26.0-nightly

**Comment by bwasty** [comment]
Hmm, it's been quite a while since I worked on this...from looking at the code again I have no idea. Perhaps I'll find some time soon to play around with it.
I guess it would also make sense to start using `wasm32-unknown-unknown` instead of the emscripten version.

**Comment by benkonz** [comment]
As it turns out, it was an issue with the rust wasm loader npm module. It was copying over the wasm file with the same naming scheme as the javascript file, when it should have copied over the wasm file with the same name. I fixed the issue and sent in a pull request to the rust wasm loader here: https://github.com/ianjsikes/rust-wasm-loader/pull/7.

I wish I could use wasm32-unknown-unknown, but I have a dependency that requires emscripten.
